### ISSUE TITLE
Rename 'Aligned organizations' to 'Community ecosystem' or similar

### ISSUE THREAD

**Issue by davenquinn** [digitalcrust/digitalcrust-website#16]
Seems like this might be a more preferable way to present this; any thoughts?

**Comment by SnirAttia** [comment]
I see what you mean. This pops in three places: the Approach text block on the front page, the Approach page, and the Aligned organizations page.

I think there's a few parts to this. DigitalCrust is to some extent hoping to create an "ecosystem"/"ecological community" of both tools/software and geoscientists/developers. Part of this also involves getting the broader geo community and folks already interested in informatics to see it as such.

I could think of phrases like "informatics ecosystem" or "community ecosystem" as you suggest.


Here's the text at the bottom of the Approach page:
"We are similar in conception to some of our [Aligned organizations]."
How about: "We are similar in concept to other efforts in the wider community [Ecosystem]."


Here's the present text in the Aligned organizations page:
"Aligned organizations
Creating an open and extensible software ecosystem for geoscience is a major endeavour, and there are many organizations involved in pushing it forward. Many of these efforts target the same overall problem as DigitalCrust, but are focused on different facets of the overall problem."

How about titling the page https://digitalcrust.org/ecosystem
"ecosystem
Creating an open and extensible software ecosystem for geoscience is a major endeavor, and many organizations are pushing forward towards this goal. Many of these efforts target the same overall problem as DigitalCrust, but are focused on different facets of the overall problem."


Here's the present text on the front page:
"It seeks to direct effort to many other [Aligned organizations](https://digitalcrust.org/aligned-organizations) that already support the geoscience software ecosystem."

How about, "It seeks to direct effort to other informatics efforts in our community [Ecosystem](https://digitalcrust.org/ecosystem) that already support the geoscience software ecosystem.


Once we settle on a preferred set of terms, I can submit push requests for changes to the above files. Also, we should add something about this "ecosystem" thinking to the bullet points at the top of the homepage and also in the "https://digitalcrust.org/software-as-collaborative-science" text that doesn't yet exist!

**Comment by davenquinn** [comment]
This could be really good. I like "Ecosystem" for this. and yeah, that link sounds good.

One as-yet undocumented note: if you clone this repository to your computer and open the website "content" directory as a "Vault" in the [Obsidian](https://obsidian.md/) app, you can change the title of the "Aligned organizations" note to "Ecosystem" and the links will auto-update in the other files that reference that one. Then you can commit the changes and make the pull request. 

You can see in the screenshot below that there are 5 links to the "Aligned organizations" page that should be updated. So that app is one of the secrets for why so many of the links on this site actually work even at this early stage!

<img width="1344" alt="image" src="https://github.com/digitalcrust/digitalcrust-website/assets/1537910/6d9157da-2e74-4344-8bb1-4710d37c1d30">

If you want to try making this change, @SnirAttia, I'd recommend experimenting with this approach.

**Comment by davenquinn** [comment]
@SnirAttia are you interested in trying to make this change? If not, it is an easy update for me to make since I have the tooling set up.

**Comment by SnirAttia** [comment]
Hey! Was quite busy with 3d geologic model data scheme stuff (fun?) then have been taking time off, currently on the Acela between New York and Boston! I can work on this sometime next week after I'm back - would be happy to try your approach with Obsidian as well to experiment with editing locally.

**Comment by davenquinn** [comment]
Awesome, no special rush! Just wanted to make sure you were on it at some point.

**Comment by SnirAttia** [comment]
Working on this now! Installed GitHub Desktop, cloned repository to my computer, and am editing the text files in Obsidian. Pretty easy so far.

**Comment by SnirAttia** [comment]
Am a bit confused, I think I may have cloned the wrong repository (SnirAttia/digitalcrust-website) to my desktop instead of the digitalcrust/digitialcrust-website. What's the best way to resolve this? Just start over from scratch?

**Comment by davenquinn** [comment]
No, this is great! You've cloned your fork, which you have "push" rights to. Then you can upload your changes to the fork, and then create a pull request to the original repository.

If you had write permissions to the original repository, you could directly upload changes to there. But this fork/pull request workflow is GitHub's major innovation and allows much more open collaboration, as you don't need prior approval to propose a change.

**Comment by SnirAttia** [comment]
Sick! Think I'm starting to get the idea of committing changes to a fork then request to pass those changes to the OG repository

**Comment by davenquinn** [comment]
Fixed this and @SnirAttia successfully validated using Obsidian to do this!
