### ISSUE TITLE
Improve "how to edit the website" page

### ISSUE THREAD

**Issue by davenquinn** [digitalcrust/digitalcrust-website#31]
This page can be improved by adding instructional content from #16. We will also need to add the ability to manage images (probably linked to an S3 bucket).

**Comment by SnirAttia** [comment]
Not sure if I'm using GitHub correctly (ha), did these changes become a pull request?

**Comment by davenquinn** [comment]
Thanks @SnirAttia! I went ahead and merged your excellent additions, and made a few small edits of my own.
