### ISSUE TITLE
url address of Get involved page is ".../contribute"

### ISSUE THREAD

**Issue by SnirAttia** [digitalcrust/digitalcrust-website#4]
To maintain consistency with the format of other url address in the webpage, the url address of the 'Get involved' page should read 
".../Get involved" rather than ".../contribute".

**Comment by davenquinn** [comment]
We'll have to change the name of the `contribute` directory to `Get involved`. Not sure if that's possible in the GitHub web interface, but if not it could be a good test case for editing your own local copy.

**Comment by SnirAttia** [comment]
Whoops! Looks like renaming the folder in the path name simply created a new folder titled "Get involved" and placed the page there. Meaning that there is now "text/content/Get involved/Get involved.md" and "text/content/contribute/Contribute to the website.md".
